### ISSUE TITLE
Research API's

### ISSUE THREAD

**Issue by tyler-stewart1026** [andrew-stehno/Project-1#3]
Using Edamam for Recipes/diet meal finder. Using YouTube for user to search for Nutrition/dieting/hot To cook videos.   Youtube is a bust, Andy will continue looking for alternate API Tuesday morning.

**Comment by andrew-stehno** [comment]
Most API's I encountered today do something similar as Edamam, but not as well.  Zapato is restaurant app that allows searching by id.  You have to search the name to get the id, then search again to get any info.  That one probably work either.  We still need one more API.

**Comment by andrew-stehno** [comment]
Der, Firebase is our second API.  Golden!
